baseurl = "/"
languageCode = "nl-NL"
defaultContentLanguage = "nl"
title = "TkkrLab"
paginate = 5
#theme = "tkkrlab"
theme = "tkkrlab-mainroad"

logo = "/site_header.png"

enableRobotsTXT = true
SectionPagesMenu = "main"
canonifyURLs = true

[Params]
  subtitle = "Hackerspace Enschede"
  description = "TkkrLab hackerspace"
  powered_by = ""
  hide_author = true
  images = []
  author = "Tkkrlab"
  copyright = ""
  avatar = "css/images/avatar.png"
  date_format = "02-01-2006"
  readmore = true
  post_navigation = true
  postSections = ["post","projects"]
  
[social]
  twitter = "tkkrlab"
  github = "tkkrlab"
  feed = "/index.xml"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 2

[Params.widgets]
    search = false
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false
    newsletter = true
    contact = true
    meta = true
    twitter = true