baseurl = "/"
languageCode = "nl-NL"
title = "TkkrLab"
paginate = 5
theme = "tkkrlab"

logo = "/site_header.png"

enableRobotsTXT = true
SectionPagesMenu = "main"
canonifyURLs = true

[params]
  description="TkkrLab hackerspace"
  powered_by = ""
  hide_author = true
  images = []
  author = "HSNL"
  copyright = ""
  avatar = "css/images/avatar.png"
  logo = "site_header.png"
  date_format = "January 02, 2006"
  
[social]
  twitter = "tkkrlab"
  github = "tkkrlab"
  feed = "/index.xml"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 2
